[PHP]
display_errors = On
error_reporting = E_ALL
date.timezone = America/Sao_Paulo
default_charset = "UTF-8"
mbstring.language = Portuguese
mbstring.internal_encoding = UTF-8

[Session]
session.name = VOX_SESSION
session.cookie_httponly = 1
session.use_strict_mode = 1
session.cookie_samesite = Lax

[opcache]
opcache.enable = 1
opcache.memory_consumption = 128
opcache.interned_strings_buffer = 8
opcache.max_accelerated_files = 4000
opcache.validate_timestamps = 1
opcache.revalidate_freq = 2

upload_max_filesize = 10M
post_max_size = 10M
memory_limit = 256M
